config/routes.rb
Trololololo::Application.routes.draw do
  resources :trolls

  root "home#index"
end

app/models/troll.rb
class Troll < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/trolls_controller.rb
class TrollsController < ApplicationController
  before_action :set_troll, only: [:show, :edit, :update, :destroy]

  # GET /trolls
  # GET /trolls.json
  def index
    @trolls = Troll.all
  end

  # GET /trolls/1
  # GET /trolls/1.json
  def show
  end

  # GET /trolls/new
  def new
    @troll = Troll.new
  end

  # GET /trolls/1/edit
  def edit
  end

  # POST /trolls
  # POST /trolls.json
  def create
    @troll = Troll.new(troll_params)

    respond_to do |format|
      if @troll.save
        format.html { redirect_to @troll, notice: 'Troll was successfully created.' }
        format.json { render action: 'show', status: :created, location: @troll }
      else
        format.html { render action: 'new' }
        format.json { render json: @troll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trolls/1
  # PATCH/PUT /trolls/1.json
  def update
    respond_to do |format|
      if @troll.update(troll_params)
        format.html { redirect_to @troll, notice: 'Troll was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @troll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trolls/1
  # DELETE /trolls/1.json
  def destroy
    @troll.destroy
    respond_to do |format|
      format.html { redirect_to trolls_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_troll
      @troll = Troll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def troll_params
      params.require(:troll).permit(:name, :bio)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trolls_helper.rb
module TrollsHelper
end

app/views/home/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to "view trolls", trolls_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trololololo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trolls/_form.html.erb
<%= form_for(@troll) do |f| %>
  <% if @troll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@troll.errors.count, "error") %> prohibited this troll from being saved:</h2>

      <ul>
      <% @troll.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trolls/edit.html.erb
<h1>Editing troll</h1>

<%= render 'form' %>

<%= link_to 'Show', @troll %> |
<%= link_to 'Back', trolls_path %>

app/views/trolls/index.html.erb
<h1>Listing trolls</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trolls.each do |troll| %>
      <tr>
        <td><%= troll.name %></td>
        <td><%= troll.bio %></td>
        <td><%= link_to 'Show', troll %></td>
        <td><%= link_to 'Edit', edit_troll_path(troll) %></td>
        <td><%= link_to 'Destroy', troll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Troll', new_troll_path %>

app/views/trolls/new.html.erb
<h1>New troll</h1>

<%= render 'form' %>

<%= link_to 'Back', trolls_path %>

app/views/trolls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @troll.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @troll.bio %>
</p>

<%= link_to 'Edit', edit_troll_path(@troll) %> |
<%= link_to 'Back', trolls_path %>